name: 'Get & Cache Dependencies'
description: 'Get the dependencies via npm and cache them'
inputs:
  caching:
    description: 'Determines whether or not to cache dependencies'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.install-deps.outputs.cache }}
runs:
  using: composite
  steps:
    - name: Cache Dependencies
      id: cache-dependencies
      if: ${{ inputs.caching == 'true' }}
      uses: actions/cache@v3
      with:
        path: node_modules
        key: example-key-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-deps
      if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' || inputs.caching != 'true' }}
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash


