name: Conditions Workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: example-key-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run failing test
        id: run-tests
        run: CI=true npm test:fail
      - name: Uploading test report
        if: ${{ failure() && steps.run-tests.outcome == 'failure' }}
        run: echo 'Uploading test report'
  report:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ github }}"



