name: Custom Actions Workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'false'
      - name: Output cache info
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Run test
        id: run-tests
        run: CI=true npm test
      - name: Deploy S3 JS
        id: deploy-s3-js
        uses: ./.github/actions/deploy-s3-js
        env:
          AWS_ACCESS_KEY_ID: 'example-key-id'
          AWS_SECRET_ACCESS_KEY: 'example-secret-access-key'
        with:
          bucket-name: example-bucket
          bucket-region: us-east-2
          dist-folder: build
      - name: Output Website URL
        run: |
          echo "Website URL: ${{ steps.deploy-s3-js.outputs.website-url }}"





