name: Custom Actions Workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'false'
      - name: Output cache info
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Run test
        id: run-tests
        run: CI=true npm test
      - name: Deploy S3 JS
        uses: ./.github/actions/deploy-s3-js





