name: Events Workflow
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print github event
        run : echo "${{ toJSON(github.event) }}"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci   # uses package.lock during install, better than npm install
      - name: Run tests
        run: CI=true npm test
  deploy:
    needs: test # depends on test job to finish successfully
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci   # uses package.lock during install, better than npm install
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."


