name: Example Action
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setyp-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci   # uses package.lock during install, better than npm install
      - name: Run tests
        run: CI=true npm test


