name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        type: string
    outputs:
      deploy-workflow-result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.deploy-job-result }}
#    secrets:
#      example-secret:
#        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-job-result: ${{ steps.set-deploy-result.deploy-step-result }}
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -la
      - name: Output Info
        run: echo "Deploying and uploading..."
      - name: Set Deploy Result
        id: set-deploy-result
        run: echo "deploy-step-result=success" >> $GITHUB_OUTPUT
