name: Use Reusable Workflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: echo "Building project..."
  deploy:
    needs: build
    uses: ./.github/workflows/reusable-workflow.yml




